# Generated by Django 5.2.5 on 2026-01-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room_bed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('Boys', 'BOYS'), ('Girls', 'GIRLS')], default='Boys', max_length=50),
        ),
    ]
